server:
  port: 9000

spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: CONVERSATION-SERVICE
          uri: lb://CONVERSATION-SERVICE
          predicates:
            - Path=/conversations/**
        - id: MESSAGE-SERVICE
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/messages/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

